language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
env:
    - DJANGO=1.10
    - DJANGO=1.11

install:
    - pip install tox-travis

script: tox

after_success:
    - pip install coveralls
    - coveralls
