language: python
python: "2.7"
env:
- TOX_ENV=py27-dj17-drf30
- TOX_ENV=py27-dj17-drf31
- TOX_ENV=py27-dj17-drf32
- TOX_ENV=py27-dj17-drf33
- TOX_ENV=py27-dj17-drf34
- TOX_ENV=py27-dj18-drf30
- TOX_ENV=py27-dj18-drf31
- TOX_ENV=py27-dj18-drf32
- TOX_ENV=py27-dj18-drf33
- TOX_ENV=py27-dj18-drf34
- TOX_ENV=py33-dj17-drf30
- TOX_ENV=py33-dj17-drf31
- TOX_ENV=py33-dj17-drf32
- TOX_ENV=py33-dj17-drf33
- TOX_ENV=py33-dj17-drf34
- TOX_ENV=py33-dj18-drf30
- TOX_ENV=py33-dj18-drf31
- TOX_ENV=py33-dj18-drf32
- TOX_ENV=py33-dj18-drf33
- TOX_ENV=py33-dj18-drf34
- TOX_ENV=py34-dj17-drf30
- TOX_ENV=py34-dj17-drf31
- TOX_ENV=py34-dj17-drf32
- TOX_ENV=py34-dj17-drf33
- TOX_ENV=py34-dj17-drf34
- TOX_ENV=py34-dj18-drf30
- TOX_ENV=py34-dj18-drf31
- TOX_ENV=py34-dj18-drf32
- TOX_ENV=py34-dj18-drf33
- TOX_ENV=py34-dj18-drf34

install:
 - pip install tox --use-mirrors
script: tox -e $TOX_ENV
after_success:
 - pip install coveralls
 - coveralls
